SELECT
    Id                                  AS patient_id,
    CAST(BIRTHDATE AS DATE)             AS birth_date,
    CAST(DEATHDATE AS DATE)             AS death_date,
    SSN                                 AS ssn,
    DRIVERS                             AS drivers_license,
    PASSPORT                            AS passport_number,
    PREFIX                              AS name_prefix,
    FIRST                               AS first_name,
    LAST                                AS last_name,
    SUFFIX                              AS name_suffix,
    MAIDEN                              AS maiden_name,
    MARITAL                             AS marital_status,
    RACE                                AS race,
    ETHNICITY                           AS ethnicity,
    GENDER                              AS gender,
    BIRTHPLACE                          AS birth_place,
    ADDRESS                             AS address,
    CITY                                AS city,
    STATE                               AS state,
    COUNTY                              AS county,
    ZIP                                 AS zip,
    CAST(LAT AS DECIMAL(10, 6))         AS latitude,
    CAST(LON AS DECIMAL(10, 6))         AS longitude,
    CAST(HEALTHCARE_EXPENSES AS DECIMAL(18, 2)) AS healthcare_expenses,
    CAST(HEALTHCARE_COVERAGE AS DECIMAL(18, 2)) AS healthcare_coverage
FROM {{ source('synthea', 'patients') }}
